import { assertCapability, detectGoogleAdsCapabilities } from "./capabilities.ts";

export type AdvancedBuild = {
  collection: string;
  operations: Array<Record<string, unknown>>;
  atomicOperations?: Array<Record<string, unknown>>;
  revertOperations: Array<Record<string, unknown>> | null;
  resourceType: string;
  resourceName: string | null;
  before: Record<string, unknown> | null;
  after: Record<string, unknown>;
  target: Record<string, unknown>;
  description: string;
  warnings: string[];
  riskLevel: "low" | "medium" | "high" | "critical";
  executable: boolean;
  blockedReason: string | null;
};

const text = (v: unknown) => String(v ?? "").trim();
const id = (v: unknown, label: string) => { const n = text(v).replace(/\D/g, ""); if (!/^\d+$/.test(n) || n === "0") throw new Error(`${label} inválido.`); return n; };
const safeArray = (v: unknown) => Array.isArray(v) ? v.map(text).filter(Boolean) : [];
const textAssets = (values: string[], existing: unknown) => values.map((value) => {
  const current = Array.isArray(existing) ? existing.find((item) => text((item as Record<string, unknown>)?.text) === value) as Record<string, unknown> | undefined : undefined;
  const pinnedField = text(current?.pinnedField);
  return { text: value, ...(pinnedField && !["UNSPECIFIED", "UNKNOWN"].includes(pinnedField) ? { pinnedField } : {}) };
});
const matchType = (v: unknown) => { const m = text(v).toUpperCase(); if (!["EXACT", "PHRASE", "BROAD"].includes(m)) throw new Error("Correspondência deve ser EXATA, FRASE ou AMPLA."); return m; };

export function buildAdGroupKeyword(target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild {
  const adGroupId = id(target.adGroupId, "ID do grupo"); const campaignId = id(target.campaignId, "ID da campanha");
  const keyword = text(target.text).replace(/\s+/g, " "); const mt = matchType(target.matchType);
  if (!keyword || keyword.length > 80 || keyword.split(/\s+/).length > 10) throw new Error("A palavra-chave deve ter entre 1 e 80 caracteres e no máximo 10 palavras.");
  if (Boolean(state.duplicate)) throw new Error("Essa palavra-chave já existe no grupo, inclusive em outro status.");
  if (Boolean(state.conflict)) throw new Error("A palavra-chave conflita com uma negativa existente no grupo/campanha.");
  const adGroup = text(state.adGroupResourceName) || `customers/${text(state.customerId)}/adGroups/${adGroupId}`;
  return { collection: "adGroupCriteria", operations: [{ create: { adGroup, status: "ENABLED", keyword: { text: keyword, matchType: mt } } }], revertOperations: null, resourceType: "keyword", resourceName: null, before: { exists: false, campaignId, adGroupId }, after: { exists: true, campaignId, adGroupId, text: keyword, matchType: mt }, target: { campaignId, adGroupId, text: keyword, matchType: mt }, description: `Adicionar “${keyword}” como palavra-chave ${mt} no grupo ${text(state.adGroupName) || adGroupId}.`, warnings: mt === "BROAD" ? ["Correspondência ampla pode expandir significativamente a intenção alcançada."] : [], riskLevel: mt === "BROAD" ? "high" : mt === "PHRASE" ? "medium" : "low", executable: Boolean(text(state.campaignResourceName)), blockedReason: null };
}

export function buildKeywordCpc(target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild {
  const resourceName = text(state.resourceName); if (!resourceName) throw new Error("Palavra-chave não encontrada.");
  const current = Number(state.currentCpcMicros); const next = Number(target.cpcMicros);
  if (!Number.isFinite(current) || current <= 0 || !Number.isFinite(next) || next <= 0) throw new Error("CPC atual e novo CPC devem ser positivos.");
  const changePercent = (next - current) / current * 100; const capabilities = detectGoogleAdsCapabilities(state);
  assertCapability(capabilities.manualCpc, capabilities.reason || "A estratégia atual não permite CPC manual.");
  if (Math.abs(changePercent) > 50) throw new Error("Ajustes de CPC acima de 50% ficam bloqueados pela política de segurança.");
  return { collection: "adGroupCriteria", operations: [{ update: { resourceName, cpcBidMicros: String(Math.round(next)) }, updateMask: "cpc_bid_micros" }], revertOperations: [{ update: { resourceName, cpcBidMicros: String(Math.round(current)) }, updateMask: "cpc_bid_micros" }], resourceType: "keyword_cpc", resourceName, before: { resourceName, cpcMicros: String(Math.round(current)), cpc: current / 1e6 }, after: { resourceName, cpcMicros: String(Math.round(next)), cpc: next / 1e6, changePercent }, target: { resourceName, cpcMicros: String(Math.round(next)), changePercent }, description: `Alterar CPC de R$ ${(current / 1e6).toFixed(2)} para R$ ${(next / 1e6).toFixed(2)}.`, warnings: ["CPC manual só terá efeito em estratégias compatíveis."], riskLevel: Math.abs(changePercent) > 20 ? "high" : "medium", executable: true, blockedReason: null };
}

function parseTime(value: unknown, label: string) { const m = text(value).match(/^(\d{2}):(00|15|30|45)$/); if (!m) throw new Error(`${label} deve usar HH:00, HH:15, HH:30 ou HH:45.`); const h = Number(m[1]); if (h > 24 || (h === 24 && m[2] !== "00")) throw new Error(`${label} fora do intervalo permitido.`); return { hour: h, minute: `MINUTE_${m[2]}` }; }
function scheduleOp(target: Record<string, unknown>, resourceName?: string) { const day = text(target.dayOfWeek).toUpperCase(); if (!["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"].includes(day)) throw new Error("Dia da semana inválido."); const start = parseTime(target.start, "Início"); const end = parseTime(target.end, "Fim"); if (start.hour * 60 + Number(start.minute.slice(-2)) >= end.hour * 60 + Number(end.minute.slice(-2))) throw new Error("O intervalo da programação deve terminar depois de começar."); return { create: { ...(resourceName ? { resourceName } : {}), campaign: text(target.campaignResourceName), adSchedule: { dayOfWeek: day, startHour: start.hour, startMinute: start.minute, endHour: end.hour, endMinute: end.minute } } }; }
export function buildAdSchedule(operation: "add_ad_schedule" | "edit_ad_schedule" | "remove_ad_schedule", target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild {
  const campaignResourceName = text(state.campaignResourceName) || text(target.campaignResourceName); if (!campaignResourceName) throw new Error("Campanha não encontrada.");
  const existing = Array.isArray(state.existingSchedules) ? state.existingSchedules : [];
  if (operation === "remove_ad_schedule") { if (existing.length <= 1) throw new Error("A remoção foi bloqueada para não deixar a campanha sem programação válida."); const resourceName = text(target.resourceName); if (!resourceName) throw new Error("Recurso da programação obrigatório."); return { collection: "campaignCriteria", operations: [{ remove: resourceName }], revertOperations: null, resourceType: "ad_schedule", resourceName, before: { schedules: existing }, after: { schedules: existing.filter((item) => text((item as Record<string, unknown>).resourceName) !== resourceName) }, target: { resourceName }, description: "Remover uma faixa da programação de anúncios.", warnings: ["A programação usa o fuso horário configurado na conta Google Ads."], riskLevel: "high", executable: true, blockedReason: null }; }
  const create = scheduleOp({ ...target, campaignResourceName });
  const startMinutes = Number(text(target.start).split(":")[0]) * 60 + Number(text(target.start).split(":")[1]);
  const endMinutes = Number(text(target.end).split(":")[0]) * 60 + Number(text(target.end).split(":")[1]);
  const overlap = existing.some((item) => { const current = item as Record<string, unknown>; return text(current.dayOfWeek) === text(target.dayOfWeek).toUpperCase() && Number(current.startMinutes) < endMinutes && Number(current.endMinutes) > startMinutes; });
  if (overlap) throw new Error("A nova faixa se sobrepõe a uma programação existente.");
  const operations = operation === "edit_ad_schedule" ? [{ remove: text(target.resourceName) }, create] : [create];
  return { collection: "campaignCriteria", operations, revertOperations: null, resourceType: "ad_schedule", resourceName: text(target.resourceName) || null, before: { schedules: existing }, after: { proposed: target }, target: { ...target, campaignResourceName }, description: operation === "edit_ad_schedule" ? "Editar faixa da programação de anúncios." : "Adicionar faixa à programação de anúncios.", warnings: ["O fuso horário aplicado é o da conta Google Ads.", ...(operation === "edit_ad_schedule" ? ["A edição é uma remoção e criação atômicas no mesmo lote."] : [])], riskLevel: "medium", executable: true, blockedReason: null };
}

export function buildLocation(operation: "add_campaign_location" | "remove_campaign_location", target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild {
  const campaign = text(state.campaignResourceName) || text(target.campaignResourceName); const geo = text(target.geoTargetConstantResourceName); if (!campaign || !/^geoTargetConstants\/\d+$/.test(geo)) throw new Error("Selecione um GeoTargetConstant oficial; IDs livres não são aceitos.");
  const existing = Array.isArray(state.existingLocations) ? state.existingLocations : [];
  if (operation === "remove_campaign_location") { if (existing.length <= 1) throw new Error("A remoção foi bloqueada para não deixar a campanha sem cobertura geográfica."); const resourceName = text(target.resourceName); if (!resourceName) throw new Error("Recurso da localização obrigatório."); return { collection: "campaignCriteria", operations: [{ remove: resourceName }], revertOperations: null, resourceType: "campaign_location", resourceName, before: { locations: existing }, after: { locations: existing.filter((x) => text((x as Record<string, unknown>).resourceName) !== resourceName) }, target: { resourceName }, description: "Remover localização da campanha.", warnings: ["Confirme que a cobertura restante atende a área pretendida."], riskLevel: "high", executable: true, blockedReason: null }; }
  if (existing.some((x) => text((x as Record<string, unknown>).geoTargetConstantResourceName) === geo)) throw new Error("Essa localização já está vinculada à campanha.");
  return { collection: "campaignCriteria", operations: [{ create: { campaign, location: { geoTargetConstant: geo } } }], revertOperations: null, resourceType: "campaign_location", resourceName: null, before: { locations: existing }, after: { locations: [...existing, { geoTargetConstantResourceName: geo, name: target.name, countryCode: target.countryCode, targetType: target.targetType }] }, target: { campaign, geoTargetConstantResourceName: geo, name: target.name, countryCode: target.countryCode, targetType: target.targetType }, description: `Adicionar localização ${text(target.name) || geo}.`, warnings: ["A localização foi selecionada por GeoTargetConstant oficial."], riskLevel: "medium", executable: true, blockedReason: null };
}

function validateRsa(target: Record<string, unknown>, state: Record<string, unknown>) { const h = safeArray(target.headlines); const d = safeArray(target.descriptions); if (h.length < 3 || h.length > 15) throw new Error("RSA deve conter entre 3 e 15 títulos."); if (d.length < 2 || d.length > 4) throw new Error("RSA deve conter entre 2 e 4 descrições."); if (h.some((x) => x.length > 30) || d.some((x) => x.length > 90)) throw new Error("Um título excede 30 caracteres ou uma descrição excede 90 caracteres."); if (new Set(h.map((x) => x.toLocaleLowerCase("pt-BR"))).size !== h.length || new Set(d.map((x) => x.toLocaleLowerCase("pt-BR"))).size !== d.length) throw new Error("Títulos e descrições não podem ser duplicados."); const resourceName = text(state.resourceName); if (!/^customers\/\d+\/ads\/\d+$/.test(resourceName) || text(state.adType) !== "RESPONSIVE_SEARCH_AD") throw new Error("O recurso selecionado não é um RSA editável."); }
function sameStringArray(left: string[], right: string[]) { return left.length === right.length && left.every((value, index) => value === right[index]); }
export function buildResponsiveSearchAd(target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild { validateRsa(target, state); const resourceName = text(state.resourceName); const finalUrls = safeArray(target.finalUrls); if (!finalUrls.length) throw new Error("Informe ao menos uma URL final."); const before = { headlines: safeArray(state.headlines), descriptions: safeArray(state.descriptions), finalUrls: safeArray(state.finalUrls), finalMobileUrls: safeArray(state.finalMobileUrls) }; const requestedMobileUrls = safeArray(target.finalMobileUrls); if (!sameStringArray(before.finalMobileUrls, requestedMobileUrls)) throw new Error("URLs mobile não podem ser alteradas ao substituir o anúncio existente. Crie um novo anúncio para usar URLs mobile diferentes."); const after = { headlines: safeArray(target.headlines), descriptions: safeArray(target.descriptions), finalUrls, finalMobileUrls: before.finalMobileUrls }; if (sameStringArray(before.headlines, after.headlines) && sameStringArray(before.descriptions, after.descriptions) && sameStringArray(before.finalUrls, after.finalUrls)) throw new Error("Nenhuma diferença foi detectada no anúncio. Edite o rascunho antes de preparar a substituição."); const adGroupId = text(target.adGroupId).replace(/\D/g, ""); const adId = text(target.adId).replace(/\D/g, ""); const identity = adGroupId && adId ? { adGroupId, adId } : {}; return { collection: "ads", operations: [{ update: { resourceName, responsiveSearchAd: { headlines: textAssets(after.headlines, state.headlineAssets), descriptions: textAssets(after.descriptions, state.descriptionAssets) }, finalUrls: after.finalUrls }, updateMask: "responsive_search_ad.headlines,responsive_search_ad.descriptions,final_urls" }], revertOperations: null, resourceType: "responsive_search_ad", resourceName, before, after, target: { ...identity, resourceName, ...after }, description: "Substituir o conteúdo do anúncio responsivo existente, mantendo o mesmo ID.", warnings: ["Fixações/pins são preservadas nos textos que permanecerem idênticos; revise textos removidos ou novos antes da confirmação.", "URLs mobile permanecem inalteradas nesta modalidade; para mudá-las, crie um novo anúncio."], riskLevel: "high", executable: true, blockedReason: null }; }

export function buildNewResponsiveSearchAd(target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild {
  validateRsa(target, state);
  const adGroup = text(state.adGroupResourceName);
  const existingAdGroupAd = text(state.adGroupAdResourceName);
  const existingStatus = text(state.adGroupAdStatus).toUpperCase();
  const finalUrls = safeArray(target.finalUrls);
  const pauseExisting = target.pauseExisting === true;
  if (!adGroup || !existingAdGroupAd) throw new Error("O grupo e o anúncio atual não foram encontrados.");
  if (!["ENABLED", "PAUSED"].includes(existingStatus)) throw new Error("O anúncio atual não está elegível para servir como referência desta criação.");
  if (!finalUrls.length) throw new Error("Informe ao menos uma URL final.");
  const ad = { headlines: safeArray(target.headlines), descriptions: safeArray(target.descriptions), finalUrls, finalMobileUrls: safeArray(target.finalMobileUrls) };
  const operations: Array<Record<string, unknown>> = [{ create: { adGroup, status: "ENABLED", ad: { responsiveSearchAd: { headlines: textAssets(ad.headlines, state.headlineAssets), descriptions: textAssets(ad.descriptions, state.descriptionAssets) }, finalUrls: ad.finalUrls, finalMobileUrls: ad.finalMobileUrls } } }];
  if (pauseExisting && existingStatus !== "PAUSED") operations.push({ update: { resourceName: existingAdGroupAd, status: "PAUSED" }, updateMask: "status" });
  return {
    collection: "adGroupAds",
    operations,
    revertOperations: null,
    resourceType: "responsive_search_ad",
    resourceName: null,
    before: { existingAd: { resourceName: existingAdGroupAd, status: existingStatus, headlines: safeArray(state.headlines), descriptions: safeArray(state.descriptions), finalUrls: safeArray(state.finalUrls), finalMobileUrls: safeArray(state.finalMobileUrls) } },
    after: { newAd: { status: "ENABLED", ...ad }, existingAd: { resourceName: existingAdGroupAd, status: pauseExisting ? "PAUSED" : existingStatus } },
    target: { adGroupId: target.adGroupId, adId: target.adId, pauseExisting, ...ad },
    description: pauseExisting ? "Criar um novo anúncio responsivo e pausar o anúncio atual na mesma operação." : "Criar um novo anúncio responsivo e manter o anúncio atual sem alterações.",
    warnings: [pauseExisting ? "O anúncio atual será pausado somente se a criação do novo anúncio também for aceita." : "Os dois anúncios permanecerão ativos e poderão participar simultaneamente dos leilões.", "Fixações/pins são copiadas para os textos idênticos; revise textos removidos ou novos antes da confirmação."],
    riskLevel: "high",
    executable: true,
    blockedReason: null,
  };
}

export function buildCampaignAsset(operation: "create_campaign_asset" | "link_campaign_asset" | "unlink_campaign_asset", target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild { const campaign = text(state.campaignResourceName) || text(target.campaignResourceName); const asset = text(state.assetResourceName) || text(target.assetResourceName); const type = text(target.assetType).toUpperCase(); if (!["SITELINK", "CALLOUT", "CALL"].includes(type)) throw new Error("Asset suportado: SITELINK, CALLOUT ou CALL."); if (operation === "create_campaign_asset") { if (type === "SITELINK" && (!text(target.text) || !text(target.finalUrl))) throw new Error("Sitelink exige texto e URL final."); if (type === "CALLOUT" && (!text(target.text) || text(target.text).length > 25)) throw new Error("Callout exige texto de até 25 caracteres."); if (type === "CALL" && !/^\+?[0-9 ()-]{8,20}$/.test(text(target.phoneNumber))) throw new Error("Número de chamada inválido."); const assetData = type === "SITELINK" ? { sitelinkAsset: { linkText: text(target.text), description1: text(target.description1), description2: text(target.description2), finalUrls: [text(target.finalUrl)], finalMobileUrls: safeArray(target.finalMobileUrls) } } : type === "CALLOUT" ? { calloutAsset: { calloutText: text(target.text) } } : { callAsset: { phoneNumber: text(target.phoneNumber), countryCode: text(target.countryCode) || "BR" } }; return { collection: "assets", operations: [{ create: assetData }], revertOperations: null, resourceType: "asset", resourceName: null, before: { exists: false }, after: { type, ...target }, target: { type, ...target }, description: `Criar asset ${type}.`, warnings: ["A criação do asset não o vincula automaticamente à campanha nesta etapa; use o vínculo após revisar o resource name retornado."], riskLevel: "medium", executable: true, blockedReason: null }; }
  if (!campaign || !asset) throw new Error("Campanha e asset são obrigatórios para o vínculo."); const link = { campaign, asset, fieldType: type === "SITELINK" ? "SITELINK" : type === "CALLOUT" ? "CALLOUT" : "CALL" }; return { collection: "campaignAssets", operations: operation === "link_campaign_asset" ? [{ create: link }] : [{ remove: text(target.campaignAssetResourceName) }], revertOperations: null, resourceType: "campaign_asset", resourceName: text(target.campaignAssetResourceName) || null, before: { linked: operation === "unlink_campaign_asset" }, after: { linked: operation === "link_campaign_asset", asset, campaign }, target: { campaign, asset, type, campaignAssetResourceName: target.campaignAssetResourceName }, description: operation === "link_campaign_asset" ? "Vincular asset à campanha." : "Remover vínculo do asset na campanha.", warnings: ["Remover vínculo não exclui o asset; assets são compartilháveis e devem ser excluídos apenas por fluxo explícito."], riskLevel: "medium", executable: true, blockedReason: null };
}

export function buildTargetOrBidding(operation: "set_target_cpa" | "set_target_roas" | "set_campaign_bidding_strategy", target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild { const resourceName = text(state.resourceName) || text(target.resourceName); if (!resourceName) throw new Error("Campanha não encontrada."); const conversions = Number(state.recentConversions || 0); if (conversions < 30) return { collection: "campaigns", operations: [], revertOperations: null, resourceType: "campaign_bidding", resourceName, before: state, after: target, target, description: "Alteração bloqueada até haver volume suficiente.", warnings: [], riskLevel: "high", executable: false, blockedReason: `AGUARDAR MAIS DADOS: há ${conversions} conversões recentes; são necessárias pelo menos 30 para esta decisão.` };
  const strategy = text(state.biddingStrategyType).toUpperCase(); if (operation === "set_target_cpa") { if (!(strategy === "MAXIMIZE_CONVERSIONS" || strategy === "TARGET_CPA")) throw new Error("A estratégia atual não suporta Target CPA."); const next = Number(target.targetCpaMicros); if (!Number.isFinite(next) || next <= 0) throw new Error("Target CPA inválido."); const field = strategy === "TARGET_CPA" ? "targetCpa" : "maximizeConversions"; const mask = strategy === "TARGET_CPA" ? "target_cpa.target_cpa_micros" : "maximize_conversions.target_cpa_micros"; return { collection: "campaigns", operations: [{ update: { resourceName, [field]: { targetCpaMicros: String(Math.round(next)) } }, updateMask: mask }], revertOperations: null, resourceType: "target_cpa", resourceName, before: { targetCpaMicros: state.targetCpaMicros }, after: { targetCpaMicros: String(Math.round(next)) }, target: { resourceName, targetCpaMicros: String(Math.round(next)) }, description: "Alterar Target CPA.", warnings: ["A alteração pode mudar o aprendizado do Smart Bidding."], riskLevel: "high", executable: true, blockedReason: null }; }
  if (operation === "set_target_roas") { if (!(strategy === "MAXIMIZE_CONVERSION_VALUE" || strategy === "TARGET_ROAS")) throw new Error("A estratégia atual não suporta Target ROAS."); const next = Number(target.targetRoas); if (!Number.isFinite(next) || next < 0.01 || next > 1000) throw new Error("Target ROAS deve estar entre 0,01 e 1000."); const field = strategy === "TARGET_ROAS" ? "targetRoas" : "maximizeConversionValue"; const mask = strategy === "TARGET_ROAS" ? "target_roas.target_roas" : "maximize_conversion_value.target_roas"; return { collection: "campaigns", operations: [{ update: { resourceName, [field]: { targetRoas: next } }, updateMask: mask }], revertOperations: null, resourceType: "target_roas", resourceName, before: { targetRoas: state.targetRoas }, after: { targetRoas: next }, target: { resourceName, targetRoas: next }, description: "Alterar Target ROAS.", warnings: ["A alteração pode mudar o aprendizado do Smart Bidding."], riskLevel: "high", executable: true, blockedReason: null }; }
  const proposed = text(target.strategy).toUpperCase(); const allowed = new Set(["MAXIMIZE_CLICKS", "MAXIMIZE_CONVERSIONS", "MAXIMIZE_CONVERSION_VALUE", "TARGET_CPA", "TARGET_ROAS", "MANUAL_CPC"]); if (!allowed.has(proposed)) throw new Error("Estratégia proposta não suportada pela S4X."); let update: Record<string, unknown>; let updateMask: string; if (proposed === "MAXIMIZE_CLICKS") { update = { resourceName, maximizeClicks: {} }; updateMask = "maximize_clicks"; } else if (proposed === "MAXIMIZE_CONVERSIONS") { update = { resourceName, maximizeConversions: {} }; updateMask = "maximize_conversions.target_cpa_micros"; } else if (proposed === "MAXIMIZE_CONVERSION_VALUE") { update = { resourceName, maximizeConversionValue: {} }; updateMask = "maximize_conversion_value.target_roas"; } else if (proposed === "TARGET_CPA") { const value = Number(target.targetCpaMicros); if (!Number.isFinite(value) || value <= 0) throw new Error("Informe Target CPA em micros ao selecionar essa estratégia."); update = { resourceName, targetCpa: { targetCpaMicros: String(Math.round(value)) } }; updateMask = "target_cpa.target_cpa_micros"; } else if (proposed === "TARGET_ROAS") { const value = Number(target.targetRoas); if (!Number.isFinite(value) || value < 0.01 || value > 1000) throw new Error("Informe Target ROAS entre 0,01 e 1000 ao selecionar essa estratégia."); update = { resourceName, targetRoas: { targetRoas: value } }; updateMask = "target_roas.target_roas"; } else { update = { resourceName, manualCpc: { enhancedCpcEnabled: Boolean(target.enhancedCpcEnabled) } }; updateMask = "manual_cpc.enhanced_cpc_enabled"; } return { collection: "campaigns", operations: [{ update, updateMask }], revertOperations: null, resourceType: "campaign_bidding", resourceName, before: { strategy }, after: { strategy: proposed }, target: { resourceName, strategy: proposed, ...(target.targetCpaMicros ? { targetCpaMicros: target.targetCpaMicros } : {}), ...(target.targetRoas ? { targetRoas: target.targetRoas } : {}) }, description: `Alterar estratégia de lances de ${strategy || "atual"} para ${proposed}.`, warnings: ["A troca de estratégia pode alterar entrega e aprendizado.", "A estratégia é enviada por seu campo de esquema oficial; bidding_strategy_type é somente leitura."], riskLevel: "high", executable: true, blockedReason: null };
}

export function buildConversionGoal(operation: "set_conversion_action_primary" | "set_conversion_action_include_in_conversions" | "set_customer_conversion_goal_biddable" | "set_campaign_conversion_goal_biddable", target: Record<string, unknown>, state: Record<string, unknown>): AdvancedBuild { const resourceName = text(state.resourceName) || text(target.resourceName); if (!resourceName) throw new Error("Meta/conversão não encontrada."); const value = target.value === true || target.biddable === true; const collection = operation === "set_customer_conversion_goal_biddable" ? "customerConversionGoals" : operation === "set_campaign_conversion_goal_biddable" ? "campaignConversionGoals" : "conversionActions"; const field = operation === "set_conversion_action_primary" ? "primaryForGoal" : operation === "set_conversion_action_include_in_conversions" ? "includeInConversionsMetric" : "biddable"; return { collection, operations: [{ update: { resourceName, [field]: value }, updateMask: field.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`) }], revertOperations: null, resourceType: "conversion_goal", resourceName, before: { [field]: state[field] }, after: { [field]: value }, target: { resourceName, value }, description: `Alterar ${field} da meta/conversão.`, warnings: ["Esta alteração pode afetar Smart Bidding e relatórios de conversões.", "Confirme todas as ações impactadas antes de prosseguir."], riskLevel: "critical", executable: true, blockedReason: null }; }
