/* eslint-disable @next/next/no-img-element */
"use client";

import { useState, type PointerEvent } from "react";
import { Crosshair, ImageIcon, Loader2, RotateCcw, Save, X } from "lucide-react";
import { BrandingLogo } from "@/components/branding/BrandingLogo";
import { DEFAULT_CLIENT_LOGO_SETTINGS, getClientLogoImageStyle, normalizeClientLogoSettings, type ClientLogoSettings } from "@/lib/client-logo-settings";

type Props = { clientName: string; dashboardName: string; logoUrl: string; initialSettings: ClientLogoSettings; saving: boolean; onClose: () => void; onSave: (settings: ClientLogoSettings) => void };

function RangeControl({ label, value, min, max, step = 1, suffix = "%", onChange }: { label: string; value: number; min: number; max: number; step?: number; suffix?: string; onChange: (value: number) => void }) {
  return <label style={{ display: "grid", gap: 7 }}><span style={{ display: "flex", justifyContent: "space-between", gap: 12, color: "#334155", fontSize: 13, fontWeight: 650 }}>{label}<strong style={{ color: "#1D4ED8" }}>{value}{suffix}</strong></span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} style={{ width: "100%", accentColor: "#2563EB" }} /></label>;
}

export function ClientLogoEditorModal({ clientName, dashboardName, logoUrl, initialSettings, saving, onClose, onSave }: Props) {
  const [settings, setSettings] = useState(() => normalizeClientLogoSettings(initialSettings));
  const imageStyle = getClientLogoImageStyle(settings);
  function setFocus(event: PointerEvent<HTMLDivElement>) {
    const rect = event.currentTarget.getBoundingClientRect();
    setSettings((current) => normalizeClientLogoSettings({ ...current, positionX: Math.round(((event.clientX - rect.left) / rect.width) * 100), positionY: Math.round(((event.clientY - rect.top) / rect.height) * 100) }));
  }
  return (
    <div role="dialog" aria-modal="true" aria-labelledby="client-logo-editor-title" style={{ position: "fixed", inset: 0, zIndex: 1200, padding: 20, background: "rgba(15,23,42,.58)", display: "flex", alignItems: "center", justifyContent: "center" }} onMouseDown={(event) => event.target === event.currentTarget && !saving && onClose()}>
      <div style={{ width: "100%", maxWidth: 980, maxHeight: "calc(100vh - 40px)", background: "#FFFFFF", borderRadius: 16, boxShadow: "0 28px 80px rgba(15,23,42,.28)", border: "1px solid #E2E8F0", overflow: "hidden", display: "flex", flexDirection: "column" }}>
        <header style={{ padding: "18px 22px", borderBottom: "1px solid #E2E8F0", display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, background: "#F8FAFC" }}><div><h2 id="client-logo-editor-title" style={{ margin: 0, display: "flex", alignItems: "center", gap: 9, color: "#0F172A", fontSize: 18, fontWeight: 750 }}><ImageIcon size={20} color="#2563EB" /> Ajustar logotipo no PDF</h2><p style={{ margin: "4px 0 0", color: "#64748B", fontSize: 13 }}>A prévia abaixo reproduz o cabeçalho do relatório em PDF.</p></div><button type="button" onClick={onClose} disabled={saving} aria-label="Fechar" style={{ width: 34, height: 34, borderRadius: 8, border: "1px solid #E2E8F0", background: "#FFFFFF", color: "#475569", display: "grid", placeItems: "center", cursor: "pointer" }}><X size={18} /></button></header>
        <main style={{ padding: 22, overflowY: "auto", display: "grid", gap: 22 }}>
          <section><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 9, flexWrap: "wrap" }}><div><h3 style={{ margin: 0, color: "#0F172A", fontSize: 14, fontWeight: 700 }}>Prévia real do cabeçalho</h3><p style={{ margin: "3px 0 0", color: "#64748B", fontSize: 12 }}>Clique dentro do logotipo para reposicionar o ponto de foco.</p></div><span style={{ padding: "5px 9px", borderRadius: 99, background: "#EFF6FF", color: "#1D4ED8", border: "1px solid #BFDBFE", fontSize: 11, fontWeight: 700 }}>A4 horizontal</span></div>
            <div style={{ padding: 14, borderRadius: 12, background: "#E8EEF8", border: "1px solid #D6E0EF", overflowX: "auto" }}><div style={{ minWidth: 760, aspectRatio: "297 / 82", background: "#EEF3FB", padding: "14px 16px", boxShadow: "0 8px 22px rgba(15,23,42,.12)" }}><div style={{ background: "linear-gradient(135deg,#0F172A,#1E40AF 58%,#2563EB)", color: "#FFFFFF", borderRadius: 16, padding: "12px 14px", display: "grid", gridTemplateColumns: "1fr 180px 150px", alignItems: "center", columnGap: 12, boxShadow: "0 18px 40px rgba(37,99,235,.18)" }}>
              <div style={{ minWidth: 0 }}><h4 style={{ margin: "0 0 4px", fontSize: 18, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{dashboardName}</h4><div style={{ display: "flex", gap: 18 }}><span style={{ fontSize: 10, opacity: .92 }}>Cliente: {clientName}</span><span style={{ fontSize: 10, opacity: .92 }}>Período: 20/08/2026 a 26/08/2026</span></div></div>
              <div onPointerDown={setFocus} title="Clique para definir o foco" style={{ position: "relative", width: 180, height: 44, background: "#FFFFFF", borderRadius: 8, overflow: "hidden", cursor: "crosshair" }}><img src={logoUrl} alt={`Prévia do logo ${clientName}`} draggable={false} style={{ display: "block", width: "100%", height: 44, ...imageStyle }} /><Crosshair size={13} style={{ position: "absolute", left: `calc(${settings.positionX}% - 6px)`, top: `calc(${settings.positionY}% - 6px)`, color: "#DC2626", filter: "drop-shadow(0 0 2px #fff)", pointerEvents: "none" }} /></div>
              <div style={{ width: 150, height: 44, display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden" }}><BrandingLogo variant="light" alt="Logo Studio 4x" style={{ width: 145, height: 34 }} fallback={<strong style={{ color: "#FFFFFF", fontSize: 17 }}>Studio 4x</strong>} /></div>
            </div></div></div>
          </section>
          <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: 22, padding: 18, borderRadius: 12, border: "1px solid #E2E8F0", background: "#FBFDFF" }}><div><h3 style={{ margin: "0 0 10px", color: "#0F172A", fontSize: 14, fontWeight: 700 }}>Modo de encaixe</h3><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>{([{"value":"contain","label":"Conter","description":"Exibe o logo inteiro"},{"value":"cover","label":"Preencher","description":"Ocupa toda a área"}] as const).map((option) => { const selected = settings.fit === option.value; return <button key={option.value} type="button" onClick={() => setSettings((current) => ({ ...current, fit: option.value }))} style={{ padding: 11, borderRadius: 9, border: selected ? "1px solid #60A5FA" : "1px solid #CBD5E1", background: selected ? "#EFF6FF" : "#FFFFFF", color: selected ? "#1D4ED8" : "#334155", textAlign: "left", cursor: "pointer" }}><strong style={{ display: "block", fontSize: 13 }}>{option.label}</strong><span style={{ display: "block", marginTop: 3, fontSize: 10, color: "#64748B" }}>{option.description}</span></button>; })}</div><button type="button" onClick={() => setSettings(DEFAULT_CLIENT_LOGO_SETTINGS)} style={{ marginTop: 12, padding: "8px 10px", borderRadius: 8, border: "1px solid #E2E8F0", background: "#FFFFFF", color: "#475569", display: "inline-flex", alignItems: "center", gap: 7, fontSize: 12, fontWeight: 650, cursor: "pointer" }}><RotateCcw size={14} /> Restaurar padrão</button></div>
            <div style={{ display: "grid", gap: 15 }}><RangeControl label="Zoom" value={Math.round(settings.zoom * 100)} min={100} max={300} step={5} onChange={(value) => setSettings((current) => ({ ...current, zoom: value / 100 }))} /><RangeControl label="Foco horizontal" value={settings.positionX} min={0} max={100} onChange={(positionX) => setSettings((current) => ({ ...current, positionX }))} /><RangeControl label="Foco vertical" value={settings.positionY} min={0} max={100} onChange={(positionY) => setSettings((current) => ({ ...current, positionY }))} /></div>
          </section>
        </main>
        <footer style={{ padding: "14px 22px", borderTop: "1px solid #E2E8F0", background: "#FFFFFF", display: "flex", justifyContent: "flex-end", gap: 9 }}><button type="button" onClick={onClose} disabled={saving} style={{ padding: "9px 14px", borderRadius: 8, border: "1px solid #E2E8F0", background: "#FFFFFF", color: "#475569", fontSize: 13, fontWeight: 650, cursor: "pointer" }}>Cancelar</button><button type="button" onClick={() => onSave(normalizeClientLogoSettings(settings))} disabled={saving} style={{ padding: "9px 15px", borderRadius: 8, border: "1px solid #2563EB", background: "#2563EB", color: "#FFFFFF", fontSize: 13, fontWeight: 700, display: "inline-flex", alignItems: "center", gap: 7, cursor: "pointer", opacity: saving ? .7 : 1 }}>{saving ? <Loader2 className="animate-spin" size={15} /> : <Save size={15} />} Aplicar ajustes</button></footer>
      </div>
    </div>
  );
}
